

# versão de compatibilidade dos comandos aqui do arquivo
# com a versão do docker-compose
version: '3'

services:
  
  node-server:
    build: .
    
    # aqui diz qual o nome do container 
    container_name: node-serverr
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    
    ports:
      - '3000:3000'
    
    depends_on: 
      - database

  # a partir desse ponto ficara os parametros do nosso banco de dados
  database:
    container_name: database
    restart: always
    image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: Junior07.01
            POSTGRES_USER: postgres
            POSTGRES_DB: perfil_dos_colaboradores
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    
  